sfu-cs-grad-buddy/config/routes.rb
Rails.application.routes.draw do
  get 'planner/index'
  get 'home/index'
    root 'home#index'
    delete 'home/index', to: 'courses_taken#destroy'
    resources :courses_taken
    resources :users
    resources :sessions, only: [:new, :create, :destroy]    
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
end

sfu-cs-grad-buddy/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @courses = Course.all
      
      @futureSemesters = CourseInstance.futureSemesters
      
      if(current_user)
        @coursesInFutureSemesters = CourseInstance.coursesInFutureSemesters(current_user.userid)
      else
        @coursesInFutureSemesters = CourseInstance.coursesInFutureSemesters(current_user)
      end
      
      
      
      
      
      if(current_user)
        @blah = CoursesTaken.completedCourses(current_user.userid)
      end
      
      
      @currentSemester = ApplicationRecord.dateToSemesterString(ApplicationRecord.currentSemester)
      
  end
end

sfu-cs-grad-buddy/app/helpers/home_helper.rb
module HomeHelper
end

sfu-cs-grad-buddy/app/views/home/index.html.erb
<%= render('static_pages/header') %>
<% if current_user %>
    Logged in as <%= current_user.userid %>.
    <%= link_to "Log Out", logout_path %>
<% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %> 
<% end %>
    
<p id="notice"><%= notice %></p>    

<h2>Welcome to CS Grad Buddy!</h2>
<%= link_to "Planner", planner_index_path %> 


<!--
<h3>Courses</h3>

<table>
  <thead>
    <tr bgcolor="#A6192E">
      <th>Name</th>
      <th></th>
      <th>Credits</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr bgcolor="#E9EFF1">
        <td><%= course.coursename %></td>
        <td><%= course.department %> <%= course.coursenumber %></td>
        <td><%= course.credits %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>

<h4>Current semester: <%= @currentSemester%></h4>

<h3>Upcoming Courses</h3>

<% @coursesInFutureSemesters.each do |semester| %>

<h4><%= semester[0] %></h4>

<table>
  <thead>
  <tr bgcolor="#A6192E">
    <th>Name</th>
     <th></th>
     <th>Instructor</th>
     <th>Credits</th>

    </tr>
  </thead>
  
    <tbody>
    <% semester[1].each do |course| %>

      <tr bgcolor="#E9EFF1">
        <td><%= course['coursename'] %></td>
        <td><%= course['department'] %> <%= course['coursenumber'] %></td>
        <td><%= course['instructor'] %></td>
        <td><%= course['credits'] %></td>
       <!-- <td><%= course['status'] %></td> -->
        <% if current_user %>

            <% if course['status'] == nil %>
                <td><%= button_to "Add to Planner", :controller => 'courses_taken', :method => :post, :action => "create", :courseinstanceid => course['courseinstanceid'] %>
            <% else %>
                <td><%= button_to "Remove from Planner", {:controller => 'courses_taken', :action => "destroy", :courseinstanceid => course['courseinstanceid']},:method => :delete %>
            <% end %>
        <% end %>


</td>

      </tr>
    <% end %>

  </tbody>

</table>

<% end %>